name: Tests
on: push
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm install
  unit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: unit-tests
        run: npm run test
